language: scala
sudo: false
scala:
   - 2.12.1
jdk:
  - oraclejdk8
script:
   - sbt ++$TRAVIS_SCALA_VERSION test scripted
   - cd examples
   - for d in */ ; do cd "$d" &&  sbt test && cd ../ ; done

